### ISSUE TITLE
Using mesmerize on hostile pawn does not clear combat target

### ISSUE THREAD

**Issue by Rufert** [Rim-Of-Madness-Team/Rim-of-Madness---Vampires#5]
This is true for both berserk player pawns and npcs. Using mez will stop the mental break. But if near a target the pawn will continue to attack if it can reach. Same with anyone who was previously meleeing it. 
So far the solution is the draft pawns and move the away, the mesmerized pawn will then function as normal.

Have not tested to see what happens if mesmerized pawn has a ranged weapon.

**Comment by SamboyCoding** [comment]
Going to take a look at this now, but it's likely it's just missing an InterruptForced.

**Comment by SamboyCoding** [comment]
So what i'm seeing, is according to rimworld's logic, when a colonist goes beserk, it will attack nearby colonists. These colonists may or may not fight back, depending on their settings and character, but once the mental break is over, the victim, who is fighting back, does not stop fighting back, and continues to hit the now no longer beserk pawn. This in turn causes the now perfectly sane colonist to fight back, again if settings/character permit, because it is being attacked.

Is this what you mean, @Rufert ?

**Comment by SamboyCoding** [comment]
If so, we would need to find any non-hostile pawn and stop it from attacking the mesmerised pawn. Which should be simple enough.

**Comment by SamboyCoding** [comment]
Ok this seems to be more than that. I InterruptForced both pawns, and they still resumed fighting. Seems as if the mental break doesn't truly end, until, as initially stated, pawns are drafted and moved away from one another.
